### PR TITLE
Changed the way of getting public IP

### PR DESCRIPTION
**Pull request by Ethaligan**
Faster, UDP based DNS connection using dig

### CODE REVIEW

**Comment by thatjpk** [comment]
Hm, using dig is neat but I don't believe this'll work on Windows.

**Comment by PierreLvx** [comment]
@thatjpk I'm interested in getting this merged. Would you welcome a PR using dig on Posix and icanhazip on Windows ?

**Comment by thatjpk** [comment]
@PierreLvx Yeah, that could work

**Comment by Ethaligan** [comment]
Or easier, a setting to chose which way is used to retrieve public IP?

**Comment by PierreLvx** [comment]
@Ethaligan Either way is fine by me.
@thatjpk Any preference ?

**Comment by thatjpk** [comment]
Yeah, there's an option in the config file to use EC2 metadata service to get your IP on AWS, so putting the switch in there seems consistent.

One of the things I've always planned on doing was refactoring stuff to make the "get my public IP" part modular.  Perhaps by classes that implement a `get_address` method or something, and a dictionary that maps a string in a config file option to the class to use.  Then adding alternative methods of fetching the IP would be pretty easy.  I haven't had time to do it myself, but if you're up for it that'd be rad. :)

**Comment by thatjpk** [comment]
Closing on account of https://github.com/thatjpk/cloudflare-ddns/pull/17
Thanks again!

**Pull request closed without merging**
